spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/fornecedor?useTimezone=true&serverTimezone=UTC
  jpa:
    show-sql: true
    hibernate:
      jdbc:
        time_zone = UTC
      ddl-auto: update
    properties.hibernate.dialect: org.hibernate.dialect.MySQL5InnoDBDialect




#spring:
#  datasource:
#    password: root
#    username: root
#    url: 'jdbc:mysql://localhost:3306/fornecedor?useTimezone=true&serverTimezone=UTC'
#  jpa:
#    hibernate:
#      ddl-auto: update




#spring:
#  application:
    #name: fornecedor
  #autoconfigure:
   # exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  #jpa:
   # hibernate:
    #  ddl-auto: update
  #datasource: 
   # driverClassName: com.mysql.cj.jdbc.Driver
    #url: jdbc:mysql://localhost:3306/fornecedor?useTimezone=true&serverTimezone=UTC
#    password: root
 #   username: root
